//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class LignesTransfere
    {
        public int codeLigne { get; set; }
        public string CodeArticle { get; set; }
        public Nullable<int> CodeTrans { get; set; }
        public Nullable<int> QuantitéNeuve { get; set; }
        public Nullable<int> QuantitéRemploi { get; set; }
        public Nullable<double> ValeurTransfert { get; set; }
    
        public virtual Article Article { get; set; }
        public virtual Transfert Transfert { get; set; }
    }
}
