//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class LigneCommande
    {
        public int CodeLign { get; set; }
        public Nullable<int> CodeCommande { get; set; }
        public string CodeArticle { get; set; }
        public Nullable<double> MontantHT { get; set; }
        public string Observation { get; set; }
        public Nullable<int> Qte { get; set; }
        public Nullable<double> Prix { get; set; }
    
        public virtual Article Article { get; set; }
        public virtual Commande Commande { get; set; }
    }
}
