//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TextileEntities : DbContext
    {
        public TextileEntities()
            : base("name=TextileEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Authentification> Authentifications { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<TblArticle> TblArticles { get; set; }
        public virtual DbSet<TblCategorie> TblCategories { get; set; }
        public virtual DbSet<TblCommande> TblCommandes { get; set; }
        public virtual DbSet<TblEntrée> TblEntrée { get; set; }
        public virtual DbSet<TblEtablissement> TblEtablissements { get; set; }
        public virtual DbSet<TblFamille> TblFamilles { get; set; }
        public virtual DbSet<TblFornisseur> TblFornisseurs { get; set; }
        public virtual DbSet<TblLigneCommande> TblLigneCommandes { get; set; }
        public virtual DbSet<TblLignesTransfere> TblLignesTransferes { get; set; }
        public virtual DbSet<TblMagasin> TblMagasins { get; set; }
        public virtual DbSet<TblPointConsommation> TblPointConsommations { get; set; }
        public virtual DbSet<TblReception> TblReceptions { get; set; }
        public virtual DbSet<TblSortie> TblSorties { get; set; }
        public virtual DbSet<TblStock> TblStocks { get; set; }
        public virtual DbSet<TblTransfert> TblTransferts { get; set; }
        public virtual DbSet<TblTypesTransfert> TblTypesTransferts { get; set; }
        public virtual DbSet<TblUnitéMesures> TblUnitéMesures { get; set; }
        public virtual DbSet<TblVille> TblVilles { get; set; }
    }
}
