//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stock
    {
        public string CodeArticle { get; set; }
        public Nullable<int> CodeMagasin { get; set; }
        public Nullable<double> Prix { get; set; }
        public Nullable<double> QteActuel { get; set; }
        public Nullable<double> QteEntré { get; set; }
        public Nullable<double> QteSortie { get; set; }
        public Nullable<double> ValeurEntré { get; set; }
        public Nullable<double> ValeurSortie { get; set; }
        public Nullable<double> RemainingStock { get; set; }
        public Nullable<bool> Statut { get; set; }
        public string Observation { get; set; }
    
        public virtual Article Article { get; set; }
        public virtual Magasin Magasin { get; set; }
    }
}
