//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblCommande
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TblCommande()
        {
            this.TblLigneCommandes = new HashSet<TblLigneCommande>();
            this.TblReceptions = new HashSet<TblReception>();
        }
    
        public int CodeCommande { get; set; }
        public Nullable<int> CodeFournisseur { get; set; }
        public Nullable<System.DateTime> DateCommande { get; set; }
        public Nullable<System.DateTime> dateLivraison { get; set; }
        public string EtatCommande { get; set; }
        public Nullable<double> MHT { get; set; }
        public Nullable<double> Remise { get; set; }
        public Nullable<double> MontantNet { get; set; }
        public Nullable<double> TVA { get; set; }
        public Nullable<double> PortEmballage { get; set; }
        public Nullable<double> MTVA { get; set; }
    
        public virtual TblFornisseur TblFornisseur { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblLigneCommande> TblLigneCommandes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblReception> TblReceptions { get; set; }
    }
}
