//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblLignesTransfere
    {
        public int codeLigne { get; set; }
        public string CodeArticle { get; set; }
        public Nullable<int> CodeTrans { get; set; }
        public Nullable<int> QuantityNeuve { get; set; }
        public Nullable<int> QuantityReemploi { get; set; }
        public Nullable<double> ValeurTransfert { get; set; }
    
        public virtual TblArticle TblArticle { get; set; }
        public virtual TblTransfert TblTransfert { get; set; }
    }
}
