//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblReception
    {
        public int numReception { get; set; }
        public Nullable<int> CodeCommande { get; set; }
        public string CodeArticle { get; set; }
        public Nullable<int> CodeFournisseur { get; set; }
        public Nullable<System.DateTime> DateReception { get; set; }
        public Nullable<int> QTELivree { get; set; }
        public Nullable<int> R_A_L { get; set; }
        public Nullable<double> Montant { get; set; }
    
        public virtual TblArticle TblArticle { get; set; }
        public virtual TblCommande TblCommande { get; set; }
        public virtual TblFornisseur TblFornisseur { get; set; }
    }
}
