//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblSortie
    {
        public int CodeSortie { get; set; }
        public Nullable<System.DateTime> DateSortie { get; set; }
        public string CodeArticle { get; set; }
        public Nullable<int> CodePointConsommation { get; set; }
        public Nullable<int> CodeMagasin { get; set; }
        public Nullable<int> QTESortie { get; set; }
        public string Observation { get; set; }
    
        public virtual TblArticle TblArticle { get; set; }
        public virtual TblMagasin TblMagasin { get; set; }
        public virtual TblPointConsommation TblPointConsommation { get; set; }
    }
}
