//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblTransfert
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TblTransfert()
        {
            this.TblLignesTransferes = new HashSet<TblLignesTransfere>();
        }
    
        public int CodeTrans { get; set; }
        public Nullable<System.DateTime> DateTrans { get; set; }
        public Nullable<int> TypeTransfer { get; set; }
        public Nullable<int> C_Magasin { get; set; }
        public Nullable<int> C_PointCons { get; set; }
        public string C_Etablissement { get; set; }
        public Nullable<double> MontantHT { get; set; }
    
        public virtual TblEtablissement TblEtablissement { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblLignesTransfere> TblLignesTransferes { get; set; }
        public virtual TblMagasin TblMagasin { get; set; }
        public virtual TblPointConsommation TblPointConsommation { get; set; }
        public virtual TblTypesTransfert TblTypesTransfert { get; set; }
    }
}
